/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Clases.FiltroAlfanumerico;
import Clases.Mensaje;
import controladores.UsuarioControlador;
import javax.swing.JOptionPane;
import interfaces.InterCambioContrasenia;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author TuKK
 */
public class CambioContraseniaVista extends javax.swing.JPanel {

    UsuarioControlador controlador = new UsuarioControlador();
    InterCambioContrasenia vista;
    private String dni;
    private String contrasenaActual;
    private boolean contraseniaIgualDni;

    public CambioContraseniaVista() {
        this(null, null, null);
    }

    public CambioContraseniaVista(String dni, String contraseniaActual, InterCambioContrasenia vista) {
        this.dni = dni;
        this.contrasenaActual = contraseniaActual;
        this.vista = vista;
        this.contraseniaIgualDni = contraseniaActual.equals(dni);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        actualLbl = new javax.swing.JLabel();
        actualValue = new javax.swing.JPasswordField();
        newLbl = new javax.swing.JLabel();
        newValue = new javax.swing.JPasswordField();
        confirmLbl = new javax.swing.JLabel();
        confirmValue = new javax.swing.JPasswordField();
        modifyBtn = new javax.swing.JButton();
        title = new javax.swing.JLabel();

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));

        actualLbl.setText("Contraseña actual:");

        if(contraseniaIgualDni) {
		    actualValue.setEditable(false);
		    actualValue.setText(contrasenaActual);
		}
        actualValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualValueActionPerformed(evt);
            }
        });

        newLbl.setText("Nueva contraseña:");

        ((AbstractDocument) newValue.getDocument()).setDocumentFilter(new FiltroAlfanumerico(60)); // Inicio el filtro Alfanumerico
        newValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newValueActionPerformed(evt);
            }
        });

        confirmLbl.setText("Confirmar contraseña:");

        ((AbstractDocument) confirmValue.getDocument()).setDocumentFilter(new FiltroAlfanumerico(60)); // Inicio el filtro Alfanumerico

        modifyBtn.setText("Modificar contraseña");
        modifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBtnActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Cambiar contraseña");
        title.setMaximumSize(new java.awt.Dimension(200, 29));
        title.setMinimumSize(new java.awt.Dimension(200, 29));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(confirmLbl)
                        .addComponent(confirmValue, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(newLbl)
                        .addComponent(actualValue, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(actualLbl)
                        .addComponent(newValue, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modifyBtn)
                .addGap(168, 168, 168))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(actualLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actualValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(modifyBtn)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actualValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualValueActionPerformed

    private void newValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newValueActionPerformed

    private void modifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBtnActionPerformed
        String actualValueStr = String.valueOf(actualValue.getPassword());
        String newValueStr = String.valueOf(newValue.getPassword());
        String confirmValueStr = String.valueOf(confirmValue.getPassword());

        System.out.println(actualValueStr + " " + newValueStr + " " + confirmValueStr + " " + dni);

        //llamo al controlador para ejecutar el cambio de contraseña, no importa el tipo de usuario
        Mensaje respuesta = controlador.cambiarContrasenia(dni, actualValueStr, newValueStr, confirmValueStr);

        if (respuesta.equals(Mensaje.EXITO)) {
            vista.forzarCambioContrasenia(false);
            actualValue.setEditable(true);
            //Reinicio temporal del filtro numerico
            ((AbstractDocument) actualValue.getDocument()).setDocumentFilter(null);
            actualValue.setText("");
            ((AbstractDocument) actualValue.getDocument()).setDocumentFilter(new FiltroAlfanumerico(60));
            
            ((AbstractDocument) newValue.getDocument()).setDocumentFilter(null);
            newValue.setText("");
            ((AbstractDocument) newValue.getDocument()).setDocumentFilter(new FiltroAlfanumerico(60));
            
            ((AbstractDocument) confirmValue.getDocument()).setDocumentFilter(null);
            confirmValue.setText("");
            ((AbstractDocument) confirmValue.getDocument()).setDocumentFilter(new FiltroAlfanumerico(60));

            JOptionPane.showMessageDialog(this, "Su contraseña se modificó con éxito", "Cambio exitoso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Hubo un error al modificar su contraseña", "Ha ocurrido un error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modifyBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualLbl;
    private javax.swing.JPasswordField actualValue;
    private javax.swing.JLabel confirmLbl;
    private javax.swing.JPasswordField confirmValue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modifyBtn;
    private javax.swing.JLabel newLbl;
    private javax.swing.JPasswordField newValue;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
