/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Clases.Mensaje;
import controladores.UsuarioControlador;
import javafx.scene.control.Alert;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author USUARIO
 */
public class CambioContrasenia extends javax.swing.JFrame {

    UsuarioControlador controlador = new UsuarioControlador();
    String dni = null;
    
    /**
     * Creates new form CambioContrasenia
     * @param dni
     */
    public CambioContrasenia(String dni) {
        initComponents();
        this.dni = dni;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actualLbl = new javax.swing.JLabel();
        actualValue = new javax.swing.JTextField();
        newLbl = new javax.swing.JLabel();
        newValue = new javax.swing.JTextField();
        confirmLbl = new javax.swing.JLabel();
        confirmValue = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        modifyBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);

        actualLbl.setText("Contraseña actual:");

        actualValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualValueActionPerformed(evt);
            }
        });

        newLbl.setText("Nueva contraseña:");

        confirmLbl.setText("Confirmar contraseña:");

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Cambiar contraseña");
        title.setMaximumSize(new java.awt.Dimension(200, 29));
        title.setMinimumSize(new java.awt.Dimension(200, 29));

        modifyBtn.setText("Modificar contraseña");
        modifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(modifyBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(actualLbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(actualValue, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmLbl)
                                    .addComponent(confirmValue, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newValue, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newLbl))))))
                .addGap(100, 100, 100))
            .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(actualLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actualValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(modifyBtn)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualValueActionPerformed

    private void modifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBtnActionPerformed
        String actualValueStr = actualValue.getText();
        String newValueStr = newValue.getText();
        String confirmValueStr = confirmValue.getText();
        
        //llamo al controlador para ejecutar el cambio de contraseña, no importa el tipo de usuario
        Mensaje respuesta = controlador.cambiarContrasenia(dni, actualValueStr, newValueStr, confirmValueStr);
                
        if(respuesta.equals(Mensaje.EXITO)) {
            JOptionPane.showMessageDialog(rootPane, "Su contraseña se modificó con éxito", "Cambio exitoso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hubo un error al modificar su contraseña", "Ha ocurrido un error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modifyBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualLbl;
    private javax.swing.JTextField actualValue;
    private javax.swing.JLabel confirmLbl;
    private javax.swing.JTextField confirmValue;
    private javax.swing.JButton modifyBtn;
    private javax.swing.JLabel newLbl;
    private javax.swing.JTextField newValue;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
