/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JLabel;
import Clases.Ticket;
import controladores.TicketControlador;
/**
 *
 * @author ramir
 */

public class VistaPreviaTicket extends javax.swing.JPanel {

    /**
     * Creates new form VistaPreviaTicket
     */
    final private Ticket ticket;
    private TicketControlador controlador;
    
    public VistaPreviaTicket(Ticket ticket) {
        initComponents();
        this.ticket = ticket;
        setAtributos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnVer = new javax.swing.JButton();
        IdLabel = new javax.swing.JLabel();
        InformadorLabel = new javax.swing.JLabel();
        TecnicoLabel = new javax.swing.JLabel();
        EstadoLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(487, 72));
        setPreferredSize(new java.awt.Dimension(689, 72));

        BtnVer.setText("Ver");
        BtnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerActionPerformed(evt);
            }
        });

        IdLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        IdLabel.setText("#####");

        InformadorLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        InformadorLabel.setText("informador nombre");

        TecnicoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TecnicoLabel.setText("tecnico nombre");

        EstadoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EstadoLabel.setText("estado Ticket");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(IdLabel)
                .addGap(40, 40, 40)
                .addComponent(InformadorLabel)
                .addGap(48, 48, 48)
                .addComponent(TecnicoLabel)
                .addGap(66, 66, 66)
                .addComponent(EstadoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(BtnVer)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnVer)
                    .addComponent(IdLabel)
                    .addComponent(InformadorLabel)
                    .addComponent(TecnicoLabel)
                    .addComponent(EstadoLabel))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerActionPerformed
        controlador.verTicket(ticket);
    }//GEN-LAST:event_BtnVerActionPerformed

    public void setIdLabel(int id){
        if(id<10){
            IdLabel.setText("0000"+id);
        }else{
            if(id<100){
                IdLabel.setText("000"+id);
            }else{
                if(id<1000){
                    IdLabel.setText("00"+id);
                }else{if (id<10000) {
                        IdLabel.setText("0"+id);
                    }else{
                        IdLabel.setText(""+id);
                    }
                }
            }
        }
    }
    
    public void setInformadorLabel(String informadorNombre){
        InformadorLabel.setText(informadorNombre);
    }
    
    public void setTecnicoLabel(String tecnicoNombre){
        TecnicoLabel.setText(tecnicoNombre);
    }
    
    public void setEstadoLabel(String estado){
        EstadoLabel.setText(estado);
    }

    public JLabel getEstadoLabel() {
        return EstadoLabel;
    }

    public JLabel getIdLabel() {
        return IdLabel;
    }

    public JLabel getInformadorLabel() {
        return InformadorLabel;
    }

    public JLabel getTecnicoLabel() {
        return TecnicoLabel;
    }
    
    public void setAtributos(){
        setIdLabel(ticket.getTicket_id());
        setInformadorLabel(ticket.getEstado());
        if(ticket.getTecnico() != null){
            setTecnicoLabel(ticket.getTecnico().getNombre());
        }else{
            setTecnicoLabel("Sin Asingar");
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVer;
    private javax.swing.JLabel EstadoLabel;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JLabel InformadorLabel;
    private javax.swing.JLabel TecnicoLabel;
    // End of variables declaration//GEN-END:variables
}
